language: node_js

node_js:
  - '14.17.3'

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn run build

cache:
  directories:
    - node_modules

before_deploy:
  - rm -rf node_modules
  - zip -r build *
  - mkdir -p deploy
  - mv build.zip deploy/build.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: social-soseol
    skip_cleanup: true
    acl: public_read
    region: ap-northeast-2
    wait-until-deploy: true
    local_dir: build

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: social-soseol # S3 버킷 이름
    key: build.zip # 파일명
    bundle_type: zip
    application: social-soseol # CodeDeploy 어플리케이션
    deployment_group: social-soseol-deploy-group # CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
