language: node_js

node_js:
  - '14.17.3'

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn run build

cache:
  directories:
    - node_modules

before_deploy:
  - echo $AWS_SECRET_ACCESS_KEY
  - echo $AWS_ACCESS_KEY_ID

deploy:
  - provider: s3
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
    bucket: social-soseol
    skip_cleanup: true
    acl: public_read
    region: ap-northeast-2
    wait-until-deploy: true
    local_dir: build
